<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Featured_s-image</name>
   <tag></tag>
   <elementGuidId>788c0043-b744-41ae-a7be-5e98f7e1d3b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search']/div/div/div/div/span[3]/div[2]/div/div/span/div/div/div[2]/div/div/div/span/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.s-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/71KR2i6-WaL._AC_UY218_.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>New Apple iMac with Retina 5K Display (27-inch, 8GB RAM, 256GB SSD Storage)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/71KR2i6-WaL._AC_UY218_.jpg 1x, https://m.media-amazon.com/images/I/71KR2i6-WaL._AC_UY327_FMwebp_QL65_.jpg 1.5x, https://m.media-amazon.com/images/I/71KR2i6-WaL._AC_UY436_FMwebp_QL65_.jpg 2x, https://m.media-amazon.com/images/I/71KR2i6-WaL._AC_UY545_FMwebp_QL65_.jpg 2.5x, https://m.media-amazon.com/images/I/71KR2i6-WaL._AC_UY654_FMwebp_QL65_.jpg 3x</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-index</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-latency</name>
      <type>Main</type>
      <value>s-product-image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-source-density</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[@class=&quot;s-desktop-width-max s-opposite-dir&quot;]/div[@class=&quot;s-desktop-content s-opposite-dir sg-row&quot;]/div[@class=&quot;sg-col-20-of-24 s-matching-dir sg-col-28-of-32 sg-col-16-of-20 sg-col sg-col-32-of-36 sg-col-8-of-12 sg-col-12-of-16 sg-col-24-of-28&quot;]/div[@class=&quot;sg-col-inner&quot;]/span[@class=&quot;rush-component s-latency-cf-section&quot;]/div[@class=&quot;s-main-slot s-result-list s-search-results sg-row&quot;]/div[@class=&quot;sg-col-20-of-24 s-result-item s-asin sg-col-0-of-12 sg-col-28-of-32 sg-col-16-of-20 sg-col sg-col-32-of-36 sg-col-12-of-16 sg-col-24-of-28&quot;]/div[@class=&quot;sg-col-inner&quot;]/span[@class=&quot;celwidget slot=MAIN template=SEARCH_RESULTS widgetId=search-results&quot;]/div[@class=&quot;s-include-content-margin s-border-bottom s-latency-cf-section&quot;]/div[@class=&quot;a-section a-spacing-medium&quot;]/div[@class=&quot;sg-row&quot;]/div[@class=&quot;sg-col-4-of-24 sg-col-4-of-12 sg-col-4-of-36 sg-col-4-of-28 sg-col-4-of-16 sg-col sg-col-4-of-20 sg-col-4-of-32&quot;]/div[@class=&quot;sg-col-inner&quot;]/div[@class=&quot;a-section a-spacing-none&quot;]/span[@class=&quot;rush-component&quot;]/a[@class=&quot;a-link-normal s-no-outline&quot;]/div[@class=&quot;a-section aok-relative s-image-fixed-height&quot;]/img[@class=&quot;s-image&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div/div/span[3]/div[2]/div/div/span/div/div/div[2]/div/div/div/span/a/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='New Apple iMac with Retina 5K Display (27-inch, 8GB RAM, 256GB SSD Storage)']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
   </webElementXpaths>
</WebElementEntity>
